"""
Counterparty name extraction for the *revenue side* of the ledger.

Customer receipts in this bank's export follow a consistent memo shape:
  <channel prefix> <customer name> <job-type keyword> <job number>
e.g. "MOBILE DEPOSIT LIBERTY DAY SCHOOL JOB 4213" -> customer "LIBERTY DAY SCHOOL".

That regularity is realistic for ACH/Zelle/mobile-deposit memos (they're
generated by the payer's own bank), so a prefix/suffix strip is reliable here.
Vendor-side card transactions ("SHELL OIL 574221", "BP#98231 NEW YORK") do NOT
follow a regular shape - those go through the vendor directory lookup instead
(see vendor_directory.py), which is how real expense-categorization tools
(Plaid, Ramp, Brex, ...) handle raw merchant descriptors.
"""
import re

# Ordered longest-first so "CHECK DEPOSIT" doesn't get shadowed by "CHECK DEP".
_PREFIXES = [
    "ONLINE TRANSFER TO",
    "ONLINE TRANSFER FROM",
    "ACH REFUND TO",
    "ACH CREDIT",
    "MOBILE DEPOSIT",
    "CHECK DEPOSIT",
    "CHECK DEP",
    "ZELLE FROM",
    "WIRE FROM",
    "WIRE",
    "AUTO PAY",
    "OWNER DISTRIBUTION",
]
_PREFIX_RE = re.compile(r"^(?:" + "|".join(_PREFIXES) + r")\s+", re.IGNORECASE)

_SUFFIXES = [
    "EQUIPMENT INSTALL",
    "SERVICE PLAN",
    "MAINT PLAN",
    "OWNER CAPITAL",
    "TAX RESERVE TRANSFER",
    "JOB",
    "SERVICE",
    "REPAIR",
    "INSTALL",
    "PROJECT",
    "INV",
]
_SUFFIX_RE = re.compile(r"\s+(?:" + "|".join(_SUFFIXES) + r")\b.*$", re.IGNORECASE)


def extract_counterparty(description: str | None) -> str | None:
    if not description:
        return None
    text = _PREFIX_RE.sub("", description.strip())
    text = _SUFFIX_RE.sub("", text)
    text = text.strip()
    return text or None
